📌 react-number-format version 5.1.4
exactly/app pull request #1093
Opened 2023-06-14 20:33 UTC by franm91

2023-06-15 16:04 UTC, JuampiRombola approved these changes

2023-06-15 20:09 UTC, cruzdanilo requested changes

2023-06-15 20:09 UTC, cruzdanilo commented on package.json
> +    "react-number-format": "~5.2.2",
please, use carret ranges

2023-06-16 13:30 UTC, cruzdanilo requested changes

2023-06-16 13:30 UTC, cruzdanilo commented on package-lock.json
> +        "react-number-format": "~5.2.2",
outdated lock

2023-06-16 13:51 UTC, cruzdanilo approved these changes

2023-06-16 14:27 UTC, jgalat approved these changes

2023-06-16 14:52 UTC, merged