✨ Web3Modal V3
exactly/app pull request #1243
Opened 2023-10-18 20:01 UTC by jgalat

This
- Introduces Web3Modal V3
- Removes packages related to V2
- Upgrades viem & wagmi

Tests:
- Tested using an injected wallet
- Tested using Wallet Connect
- Tested using Safe

2023-10-18 20:27 UTC, cruzdanilo requested changes

2023-10-18 20:27 UTC, cruzdanilo commented on utils/client.ts
> +        ]),
add [coinbase wallet](https://wagmi.sh/react/connectors/coinbaseWallet) (as the second option) and [ledger](https://wagmi.sh/react/connectors/ledger) connectors.

2023-10-19 13:13 UTC, cruzdanilo submitted a review, later dismissed

2023-10-19 13:42 UTC, cruzdanilo approved these changes

2023-10-19 16:40 UTC, cruzdanilo submitted a review, later dismissed

2023-10-19 17:54 UTC, cruzdanilo approved these changes

2023-10-19 18:18 UTC, franm91 approved these changes

2023-10-19 18:18 UTC, merged

2023-10-19 18:19 UTC, sebipap approved these changes
code lgtm